# =================================================================
#
# Terms and Conditions of Use
#
# Unless otherwise noted, computer program source code of this
# distribution is covered under Crown Copyright, Government of
# Canada, and is distributed under the MIT License.
#
# The Canada wordmark and related graphics associated with this
# distribution are protected under trademark law and copyright law.
# No permission is granted to use them outside the parameters of
# the Government of Canada's corporate identity program. For
# more information, see
# http://www.tbs-sct.gc.ca/fip-pcim/index-eng.asp
#
# Copyright title to all 3rd party software distributed with this
# software is held by the respective copyright holders as noted in
# those files. Users are asked to read the 3rd Party Licenses
# referenced with those assets.
#
# Copyright (c) 2016 Government of Canada
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

BASEDIR=$(shell pwd)
STAGE=$(BASEDIR)/stage

help:
	@echo "Please use \`make <target>\` where <target> is one of"
	@echo " setup:               configures the install"
	@echo " clean:               removes files generated by the build/install"

setup: deps docs

docs:
	mkdocs build

deps: build
	bash -f bin/install_deps.sh $(BASEDIR)

serve:
	mkdocs serve -a 0.0.0.0:8000

clean:
	rm -fr $(STAGE)
	rm -fr $(BASEDIR)/woudc_theme/static/libs
	rm -fr $(BASEDIR)/site/
	rm -fr /tmp/woudc-guidebook

build:
	mkdir -p $(BASEDIR)/woudc_theme/static/libs/js
	mkdir -p $(BASEDIR)/woudc_theme/static/libs/css

publish:
	git clone git@github.com:woudc/woudc-guidebook.git /tmp/woudc-guidebook
	cd /tmp/woudc-guidebook
	git checkout gh-pages
	#echo "guide.woudc.org" > site/CNAME
	/bin/cp -rp $(BASEDIR)/site/* .
	git add .
	git commit -am 'update guidebook'
	git push origin gh-pages

.PHONY: help setup docs deps serve clean build publish
